# Generated by Django 2.2.6 on 2020-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='power',
            field=models.IntegerField(default=0),
        ),
    ]
