# Generated by Django 2.2.6 on 2020-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_experts_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experts',
            name='patients',
        ),
        migrations.AddField(
            model_name='experts',
            name='patients',
            field=models.ManyToManyField(related_name='my_experts', to='test_app.MyUser'),
        ),
        migrations.RemoveField(
            model_name='volunteers',
            name='patients',
        ),
        migrations.AddField(
            model_name='volunteers',
            name='patients',
            field=models.ManyToManyField(related_name='my_volunteers', to='test_app.MyUser'),
        ),
    ]
