# Generated by Django 3.0.5 on 2020-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-helpfulVote', '-created')},
        ),
        migrations.AddField(
            model_name='review',
            name='helpfulVote',
            field=models.IntegerField(default=0),
        ),
    ]
