# Generated by Django 3.0.5 on 2020-05-06 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answer', '0002_auto_20200502_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='articlesLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
