# Generated by Django 2.1.7 on 2019-04-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='articlepost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/%Y%m%d/'),
        ),
    ]
